// Shared content for the Roger Winter portfolio (home + sub-pages).
window.PORTFOLIO = {
  name: "Roger Winter",
  tagline: "AI-native developer & technical content creator",
  blurb: "I build AI-native software and write the tutorials that teach people how it works. Below are the projects I ship and document — explore the writeups, try the live demos, read the code.",
  email: "hello@rogerwinter.dev",
  social: [
    { label: "GitHub", href: "https://github.com/RealRogerWinter", handle: "RealRogerWinter" },
    { label: "LinkedIn", href: "#linkedin", handle: "in/rogerwinter" },
    { label: "X / Twitter", href: "#x", handle: "@rogerwinter" },
    { label: "Twitch", href: "#twitch", handle: "twitch.tv/pricey" },
  ],
  projects: [
    {
      id: "sheet-llm",
      name: "sheet-llm",
      n: "01",
      status: "In development",
      desc: "A sheet music notation editor you talk to: describe music in plain language and an LLM orchestrator edits the score, changing only the bars it's asked to.",
      tagline: "Compose, edit, and reason about musical scores in plain language.",
      tags: ["Music", "LLM", "Editor"],
      clef: true,
      demo: "#demo",
      repo: "https://github.com/RealRogerWinter/sheet-llm",
      overview: [
        "sheet-llm is a notation editor built around a language model. Instead of placing every note by hand, you describe what you want — \u201cadd a four-bar ii\u2013V\u2013I in F\u201d, \u201ctranspose the bridge up a third\u201d, \u201charmonize this melody as a chorale\u201d — and the score updates in place.",
        "The goal is to make notation feel like a conversation with a musician who can also read and write standard sheet music, while every edit stays fully manual-overridable on the canvas.",
      ],
      features: [
        { h: "Plain-language editing", p: "Describe changes in words; the model turns intent into precise score edits you can inspect, tweak, and undo." },
        { h: "Structured score model", p: "Notes, voices, and dynamics live in a typed document the model reads and writes — not a black-box image." },
        { h: "Manual + AI together", p: "Drag, click, and type as usual. The assistant is one more tool, never a wall between you and the page." },
        { h: "Export anywhere", p: "Render to MusicXML and MIDI so scores move cleanly into the rest of your workflow." },
      ],
      stack: ["TypeScript", "React", "Web Audio", "LLM API", "MusicXML"],
    },
    {
      id: "onestreamer",
      name: "OneStreamer",
      n: "02",
      status: "Live",
      desc: "A live-streaming platform where only one person streams at a time, and anyone watching can cut in to take over. Real people and AI viewers fill the chat.",
      tagline: "A live-streaming platform where anyone can seize the broadcast, watched by real people and AI viewers alike.",
      tags: ["Streaming", "AI Agents", "Realtime"],
      logo: "portfolio/assets/onestreamer.png", logoBg: "#000000",
      demo: "https://onestreamer.live",
      repo: "https://github.com/RealRogerWinter/onestreamer",
      overview: [
        "OneStreamer flips the streaming model: at any moment, only a single human can hold the stage. Everyone else in the room is an AI viewer that watches the feed, reacts, and fills the chat in real time.",
        "It\u2019s a study in what \u201clive\u201d feels like when the audience is synthetic — agents with personalities, opinions, and memory that respond to what\u2019s actually happening on screen.",
      ],
      features: [
        { h: "One live seat", p: "A single broadcaster at a time; the floor passes between humans instead of fragmenting into endless parallel streams." },
        { h: "AI audience", p: "Viewer agents watch the stream and generate reactions and chat grounded in the current moment." },
        { h: "Real-time chat", p: "Comments stream back with low latency, so the broadcaster feels a living room — not a render queue." },
        { h: "Personality & memory", p: "Each viewer keeps a consistent voice across a session, building running jokes and callbacks." },
      ],
      stack: ["WebRTC", "Node", "WebSockets", "LLM Agents", "React"],
    },
    {
      id: "price-games",
      name: "Price Games",
      n: "03",
      status: "Live",
      desc: "A free browser game for guessing real Amazon prices, with seven modes and live multiplayer. Built test-first, end to end, by Claude Code agents.",
      tagline: "Free, fast pricing games in the browser — and a lab for engagement and AI pipelines.",
      tags: ["Games", "Web"],
      logo: "portfolio/assets/price-games.png", logoBg: "#14152b",
      demo: "https://price.games",
      repo: "#repo",
      overview: [
        "Price Games is a collection of quick, browser-based games built around guessing and bidding on prices. No install, no account — open a tab and play.",
        "It also doubles as the arena that Pricey (the AI streamer) competes in, so the same game engine powers both human and machine players.",
      ],
      features: [
        { h: "Instant play", p: "Pure web. Load a page and you\u2019re in — nothing to download or sign up for." },
        { h: "Multiple modes", p: "Guess-the-price, bidding rounds, and beat-the-market variants." },
        { h: "Shared engine", p: "The same rules humans play also drive the Pricey neural-net agent." },
        { h: "Built to embed", p: "Lightweight enough to drop into a stream overlay or a tutorial." },
      ],
      stack: ["TypeScript", "Canvas", "Vite", "Web"],
    },
    {
      id: "pricey",
      name: "Pricey",
      n: "04",
      status: "Live on Twitch",
      desc: "A piggy-bank streamer with a small neural network for a brain, training itself to guess product prices live on Price Games as it plays.",
      tagline: "A 24/7 AI streamer that plays Price Games on a hand-rolled neural net, and has feelings about it.",
      tags: ["Neural Net", "Twitch", "AI"],
      logo: "portfolio/assets/pricey.webp", logoBg: "#1d1518",
      demo: "https://www.twitch.tv/pricegamespricey",
      repo: "#repo",
      overview: [
        "Pricey is an autonomous Twitch streamer: a neural network that plays Price Games on camera and gets measurably better as it goes. Viewers watch the model reason, guess, and adjust in real time.",
        "It\u2019s equal parts product and teaching tool — the learning curve is the show, and the writeups break down exactly how the network improves.",
      ],
      features: [
        { h: "Learns on stream", p: "A neural network that updates its play as rounds accumulate — the progress is the entertainment." },
        { h: "Autonomous broadcast", p: "Drives its own Twitch presence: playing, narrating, and reacting without a human at the wheel." },
        { h: "Plays Price Games", p: "Competes in the same browser games humans play, on the shared engine." },
        { h: "Transparent by design", p: "Tutorials document the architecture and training, so the black box stays open." },
      ],
      stack: ["Python", "PyTorch", "Twitch API", "WebSockets"],
    },
    {
      id: "multilingual-seo",
      name: "Multilingual SEO Tool",
      n: "05",
      status: "In development",
      desc: "Give it a URL and it checks real search demand for intent-preserving keyword translations, ranking what's actually worth translating per locale.",
      tagline: "Research, generate, and optimize content across languages from one workspace.",
      tags: ["SEO", "i18n", "Content"],
      demo: "#demo",
      repo: "https://github.com/RealRogerWinter/multilingual-seo",
      overview: [
        "Multilingual SEO Tool helps content teams rank in more than one language. It pulls locale-aware keyword research, drafts optimized copy, and manages translated metadata side by side.",
        "The aim is to make \u201cdo SEO in five markets\u201d feel like one coherent workflow instead of five disconnected ones.",
      ],
      features: [
        { h: "Locale-aware research", p: "Keyword data scoped to each target language and region — not a single English baseline." },
        { h: "Optimized drafting", p: "Generate copy tuned to the keywords and search intent of each locale." },
        { h: "Metadata management", p: "Titles, descriptions, and hreflang handled per language in one place." },
        { h: "One workspace", p: "Plan, write, and ship across markets without juggling separate tools." },
      ],
      stack: ["TypeScript", "Next.js", "LLM API", "Search APIs"],
    },
  ],
};
