#!/usr/bin/env python3
"""
Build the deployable static site (`site/`) from the Claude Design export.

The design export is a multi-page React artifact that renders client-side via
Babel-in-browser. This script migrates it into a clean, self-contained static
site:

  * keeps the *real* pages (home, bio, contact, 5 project pages) and the JSX
    component graph they import; drops design-tool exploration artifacts
    (Nav Variants, Portfolio Explorations, design-canvas, directions/,
    site_terminal_backup, project.jsx, navvariants) and the unused
    screenshots/ + uploads/ originals;
  * renames the awkward "Roger Winter - Portfolio.html" -> index.html and sets
    HOME_FILE -> "/" (the export shipped HOME_FILE with an em-dash that does not
    match the hyphen in the real filename, so every nav/back link would 404 as a
    static site);
  * lowercases Bio.html/Contact.html -> bio.html/contact.html and fixes the few
    cross-references;
  * rewrites the three unpkg CDN <script> tags to self-hosted /vendor/* (React
    switched dev->prod min; semantically identical render, smaller + no console
    noise; Babel standalone kept verbatim);
  * injects per-page SEO/OpenGraph/Twitter meta + canonical + favicon;
  * emits favicon.svg, robots.txt, sitemap.xml.

Input : SRC (extracted design export)         -- not committed
Output: DST (committed, deployable static site)

Re-runnable and idempotent. Vendor files are downloaded by a separate step
(scripts/fetch-vendor.sh) so this script needs no network.
"""
import os, re, shutil, html, sys

SRC = "/home/claudeuser/design-src/extracted"
DST = "/home/claudeuser/rogerwinter-dev/site"
CANON = "https://rogerwinter.dev"

# --- component graph actually used by the real pages -------------------------
JSX_ROOT = ["tweaks-panel.jsx"]
JSX_PORTFOLIO = [
    "data.jsx", "shell.jsx", "microviz.jsx",          # shared
    "site.jsx",                                        # home
    "bio.jsx", "contact.jsx",                          # bio / contact
    "seo-viz.jsx", "seo-demo.jsx", "seotool.jsx",      # multilingual-seo
    "os-diagrams.jsx", "onestreamer.jsx",              # onestreamer
    "pg-diagrams.jsx", "pricegames.jsx",               # price-games
    "pricey-viz.jsx", "pricey-mood.jsx", "pricey.jsx", # pricey
    "sl-diagrams.jsx", "sl-flows.jsx", "sl-chat.jsx", "sheetllm.jsx",  # sheet-llm
]

# --- page rename map (export filename -> deployed filename) ------------------
PAGES = {
    "Roger Winter - Portfolio.html": "index.html",
    "Bio.html": "bio.html",
    "Contact.html": "contact.html",
    "project-multilingual-seo.html": "project-multilingual-seo.html",
    "project-onestreamer.html": "project-onestreamer.html",
    "project-price-games.html": "project-price-games.html",
    "project-pricey.html": "project-pricey.html",
    "project-sheet-llm.html": "project-sheet-llm.html",
}

# Branded social card (RW monogram) — generated by scripts/make-og-image.py.
# Used as the share preview for the non-project pages; project pages keep their
# own screenshots. Regenerate the PNG with that script if the brand changes.
OG_COVER = "/portfolio/assets/og-cover.png"
OG_COVER_ALT = "Roger Winter — AI-native developer & technical content creator"

# --- per-page metadata (descriptions pulled from the design's data.jsx) ------
META = {
    "index.html": dict(
        desc="I build AI-native software and write the tutorials that teach people how it works — the projects I ship and document, with writeups, live demos, and code.",
        img=OG_COVER, img_w=1200, img_h=630, img_type="image/png", img_alt=OG_COVER_ALT,
        type="website"),
    "bio.html": dict(
        desc="About Roger Winter — an AI-native developer and technical content creator.",
        img=OG_COVER, img_w=1200, img_h=630, img_type="image/png", img_alt=OG_COVER_ALT,
        type="website"),
    "contact.html": dict(
        desc="Get in touch with Roger Winter — AI-native developer and technical content creator.",
        img=OG_COVER, img_w=1200, img_h=630, img_type="image/png", img_alt=OG_COVER_ALT,
        type="website"),
    "project-multilingual-seo.html": dict(
        desc="Give it a URL and it checks real search demand for intent-preserving keyword translations, ranking what's actually worth translating per locale.",
        img="/portfolio/assets/seo-results.png", type="article"),
    "project-onestreamer.html": dict(
        desc="A live-streaming platform where only one person streams at a time, and anyone watching can cut in to take over. Real people and AI viewers fill the chat.",
        img="/portfolio/assets/onestreamer.png", type="article"),
    "project-price-games.html": dict(
        desc="A free browser game for guessing real Amazon prices, with seven modes and live multiplayer. Built test-first, end to end, by Claude Code agents.",
        img="/portfolio/assets/pg-hero.png", type="article"),
    "project-pricey.html": dict(
        desc="A piggy-bank streamer with a small neural network for a brain, training itself to guess product prices live on Price Games as it plays.",
        img="/portfolio/assets/pricey.webp", type="article"),
    "project-sheet-llm.html": dict(
        desc="A sheet music notation editor you talk to: describe music in plain language and an LLM orchestrator edits the score, changing only the bars it's asked to.",
        img="/portfolio/assets/sl-compose.png", type="article"),
}

FAVICON = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <!-- Matches the site's header monogram: dark badge, accent-green border, green "RW" -->
  <rect x="0.9" y="0.9" width="30.2" height="30.2" rx="8" fill="#0b0d0c"
        stroke="#3d945c" stroke-width="1.8"/>
  <text x="16" y="20.5" font-family="'Syne','Arial Black',system-ui,sans-serif"
        font-size="13" font-weight="800" text-anchor="middle" fill="#57f08d">RW</text>
</svg>
"""

def die(msg):
    print("BUILD ERROR:", msg); sys.exit(1)

def reset_dst():
    if os.path.isdir(DST):
        shutil.rmtree(DST)
    os.makedirs(os.path.join(DST, "portfolio"))
    os.makedirs(os.path.join(DST, "vendor"), exist_ok=True)

def copy_jsx():
    for f in JSX_ROOT:
        shutil.copy2(os.path.join(SRC, f), os.path.join(DST, f))
    for f in JSX_PORTFOLIO:
        s = os.path.join(SRC, "portfolio", f)
        if not os.path.exists(s):
            die(f"missing expected jsx: {s}")
        shutil.copy2(s, os.path.join(DST, "portfolio", f))
    # assets
    shutil.copytree(os.path.join(SRC, "portfolio", "assets"),
                    os.path.join(DST, "portfolio", "assets"))

def patch_shell_and_bio():
    # shell.jsx: HOME_FILE -> "/", lowercase Bio/Contact nav targets
    p = os.path.join(DST, "portfolio", "shell.jsx")
    t = open(p, encoding="utf-8").read()
    t2 = re.sub(r'HOME_FILE\s*=\s*"[^"]*"', 'HOME_FILE = "/"', t, count=1)
    if t2 == t: die("shell.jsx: HOME_FILE assignment not found")
    t2 = t2.replace('href:"Bio.html"', 'href:"bio.html"')
    t2 = t2.replace('href="Contact.html"', 'href="contact.html"')
    open(p, "w", encoding="utf-8").write(t2)
    # bio.jsx: Contact.html -> contact.html
    p = os.path.join(DST, "portfolio", "bio.jsx")
    t = open(p, encoding="utf-8").read()
    open(p, "w", encoding="utf-8").write(t.replace('href="Contact.html"', 'href="contact.html"'))

VENDOR_SUBS = [
    (re.compile(r'<script[^>]*\breact-dom\.development\.js\b[^>]*>\s*</script>'),
     '<script src="/vendor/react-dom.production.min.js"></script>'),
    (re.compile(r'<script[^>]*\breact\.development\.js\b[^>]*>\s*</script>'),
     '<script src="/vendor/react.production.min.js"></script>'),
    (re.compile(r'<script[^>]*\bbabel\.min\.js\b[^>]*>\s*</script>'),
     '<script src="/vendor/babel.min.js"></script>'),
]

def build_meta_block(out_name, title):
    m = META[out_name]
    url = CANON + "/" + ("" if out_name == "index.html" else out_name)
    e = lambda s: html.escape(s, quote=True)
    img_abs = (CANON + m["img"]) if m["img"] else None
    L = [
        f'<meta name="description" content="{e(m["desc"])}" />',
        f'<link rel="canonical" href="{e(url)}" />',
        '<link rel="icon" type="image/svg+xml" href="/favicon.svg" />',
        '<meta name="theme-color" content="#0b0d0c" />',
        f'<meta name="author" content="Roger Winter" />',
        f'<meta property="og:type" content="{m["type"]}" />',
        '<meta property="og:site_name" content="Roger Winter" />',
        f'<meta property="og:title" content="{e(title)}" />',
        f'<meta property="og:description" content="{e(m["desc"])}" />',
        f'<meta property="og:url" content="{e(url)}" />',
    ]
    if img_abs:
        L.append(f'<meta property="og:image" content="{e(img_abs)}" />')
        if m.get("img_type"):
            L.append(f'<meta property="og:image:type" content="{m["img_type"]}" />')
        if m.get("img_w") and m.get("img_h"):
            L.append(f'<meta property="og:image:width" content="{m["img_w"]}" />')
            L.append(f'<meta property="og:image:height" content="{m["img_h"]}" />')
        if m.get("img_alt"):
            L.append(f'<meta property="og:image:alt" content="{e(m["img_alt"])}" />')
    L.append(f'<meta name="twitter:card" content="{"summary_large_image" if img_abs else "summary"}" />')
    L.append(f'<meta name="twitter:title" content="{e(title)}" />')
    L.append(f'<meta name="twitter:description" content="{e(m["desc"])}" />')
    if img_abs:
        L.append(f'<meta name="twitter:image" content="{e(img_abs)}" />')
        if m.get("img_alt"):
            L.append(f'<meta name="twitter:image:alt" content="{e(m["img_alt"])}" />')
    return "\n" + "\n".join(L) + "\n"

def transform_pages():
    for src_name, out_name in PAGES.items():
        sp = os.path.join(SRC, src_name)
        if not os.path.exists(sp): die(f"missing page: {sp}")
        h = open(sp, encoding="utf-8").read()
        # vendor swap (assert each happened exactly once)
        for rx, repl in VENDOR_SUBS:
            h, n = rx.subn(repl, h)
            if n != 1:
                die(f"{src_name}: expected 1 vendor swap for {repl!r}, did {n}")
        # title for og
        mt = re.search(r"<title>(.*?)</title>", h, re.S)
        title = mt.group(1).strip() if mt else "Roger Winter"
        # inject meta before </head>
        if "</head>" not in h: die(f"{src_name}: no </head>")
        h = h.replace("</head>", build_meta_block(out_name, title) + "</head>", 1)
        open(os.path.join(DST, out_name), "w", encoding="utf-8").write(h)

def emit_extras():
    open(os.path.join(DST, "favicon.svg"), "w", encoding="utf-8").write(FAVICON)
    open(os.path.join(DST, "robots.txt"), "w", encoding="utf-8").write(
        "User-agent: *\nAllow: /\n\nSitemap: %s/sitemap.xml\n" % CANON)
    urls = []
    for out_name in PAGES.values():
        loc = CANON + "/" + ("" if out_name == "index.html" else out_name)
        urls.append(f"  <url><loc>{html.escape(loc)}</loc></url>")
    open(os.path.join(DST, "sitemap.xml"), "w", encoding="utf-8").write(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(urls) + "\n</urlset>\n")

def verify_links():
    """Catch broken inter-page <a href="*.html"> links that curl can't see
    (they're rendered client-side from JSX)."""
    present = set(os.listdir(DST))
    bad = []
    for root, _, files in os.walk(os.path.join(DST, "portfolio")):
        for f in files:
            if not f.endswith(".jsx"): continue
            t = open(os.path.join(root, f), encoding="utf-8").read()
            for href in re.findall(r'href="([^"#{][^"]*\.html)"', t):
                if href not in present:
                    bad.append((f, href))
    # also resolve project-${id}.html for known ids
    ids = ["sheet-llm","onestreamer","price-games","pricey","multilingual-seo"]
    for i in ids:
        if f"project-{i}.html" not in present:
            bad.append(("data.jsx", f"project-{i}.html"))
    if bad:
        die("broken static html links: " + repr(bad))

def main():
    reset_dst()
    copy_jsx()
    patch_shell_and_bio()
    transform_pages()
    emit_extras()
    verify_links()
    # report
    total = 0
    for root,_,files in os.walk(DST):
        for f in files: total += os.path.getsize(os.path.join(root,f))
    print("OK: built", DST)
    print("  pages:", ", ".join(sorted(PAGES.values())))
    print("  jsx  :", len(JSX_ROOT)+len(JSX_PORTFOLIO), "components")
    print("  size : %.1f MB (excl. vendor downloads)" % (total/1e6))

if __name__ == "__main__":
    main()
