// Extract the CSS-in-JS template-literal blocks from the window-global source
// components into static stylesheets — the single source of truth that migrated
// Astro pages link, instead of injecting CSS via React.
//
// The blocks are plain static template literals (no ${} interpolation), so a
// straight slice between backticks is faithful. tests/css-extract.test.js asserts
// the committed files match what this produces (drift guard). Re-runnable; run
// `node scripts/extract-css.mjs` after editing any of the source CSS.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');

// out file (under src/styles) <- CSS const blocks from a window-global source.
// A sheet is drift-guarded only while its source still exists (used by an
// un-migrated page). Once a page is fully migrated to Astro and its source .jsx
// is removed, its stylesheet becomes standalone and drops off this list
// (home.css did, when site.jsx was removed).
export const SHEETS = [
  { out: 'shell.css', src: 'site/portfolio/shell.jsx', blocks: ['BASE_CSS', 'SUBPAGE_CSS', 'RW_CSS'], label: 'shell (chrome + subpage + rw)' },
  { out: 'microviz.css', src: 'site/portfolio/microviz.jsx', blocks: ['MV_CSS'], label: 'micro-visualizations' },
];

function literal(src, name) {
  const m = src.match(new RegExp('const\\s+' + name + '\\s*=\\s*`'));
  if (!m) throw new Error(`extract-css: ${name} not found`);
  const start = m.index + m[0].length - 1; // the opening backtick
  const end = src.indexOf('`', start + 1);
  if (end < 0) throw new Error(`extract-css: ${name} template literal unterminated`);
  return src.slice(start + 1, end).trim();
}

export function buildCss(sheet) {
  const src = fs.readFileSync(path.join(ROOT, sheet.src), 'utf8');
  const body = sheet.blocks.map((b) => literal(src, b)).join('\n\n');
  return (
    `/* ${sheet.label} CSS — generated by scripts/extract-css.mjs from\n` +
    `   ${sheet.src} (${sheet.blocks.join(' + ')}). Do not edit by hand; re-run the\n` +
    '   script. The drift guard test keeps this in sync. */\n\n' +
    body +
    '\n'
  );
}

if (process.argv[1] && url.pathToFileURL(process.argv[1]).href === import.meta.url) {
  for (const sheet of SHEETS) {
    const out = path.join(ROOT, 'src', 'styles', sheet.out);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, buildCss(sheet));
    console.log(`wrote src/styles/${sheet.out} (${buildCss(sheet).length} bytes)`);
  }
}
