// Extract the shared shell CSS (BASE_CSS + SUBPAGE_CSS + RW_CSS) from the
// window-global shell.jsx into a single static stylesheet — the single source of
// truth that migrated Astro pages link, instead of injecting CSS via React.
//
// The blocks are plain static template literals (no ${} interpolation), so a
// straight slice between backticks is faithful. tests/css-extract.test.js asserts
// the committed src/styles/shell.css matches what this produces (drift guard).
// Re-runnable; run `node scripts/extract-css.mjs` after editing shell.jsx CSS.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const SHELL = path.join(ROOT, 'site', 'portfolio', 'shell.jsx');
const OUT = path.join(ROOT, 'src', 'styles', 'shell.css');
const BLOCKS = ['BASE_CSS', 'SUBPAGE_CSS', 'RW_CSS'];

function literal(src, name) {
  const m = src.match(new RegExp('const\\s+' + name + '\\s*=\\s*`'));
  if (!m) throw new Error(`extract-css: ${name} not found in shell.jsx`);
  const start = m.index + m[0].length - 1; // the opening backtick
  const end = src.indexOf('`', start + 1);
  if (end < 0) throw new Error(`extract-css: ${name} template literal unterminated`);
  return src.slice(start + 1, end).trim();
}

export function buildShellCss() {
  const src = fs.readFileSync(SHELL, 'utf8');
  const body = BLOCKS.map((b) => literal(src, b)).join('\n\n');
  return (
    '/* Shared shell CSS — generated by scripts/extract-css.mjs from\n' +
    '   site/portfolio/shell.jsx (BASE_CSS + SUBPAGE_CSS + RW_CSS). Do not edit by\n' +
    '   hand; re-run the script. The drift guard test keeps this in sync. */\n\n' +
    body +
    '\n'
  );
}

if (process.argv[1] && url.pathToFileURL(process.argv[1]).href === import.meta.url) {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, buildShellCss());
  console.log(`wrote ${path.relative(ROOT, OUT)} (${buildShellCss().length} bytes)`);
}
