#!/usr/bin/env python3
"""Self-host the Google Fonts the site uses.

Fetches the same css2 the pages requested (with a modern-browser UA so Google
returns woff2), keeps only the subsets the site actually renders (latin,
latin-ext, and Noto Music's `music` subset for the clef glyph), downloads each
woff2 into site/vendor/fonts/, and writes a fonts.css with local URLs.

Re-runnable. Output (woff2 + fonts.css) is committed; this script needs network
and is run only when the font set changes. Companion to scripts/fetch-vendor.sh.
"""
import glob
import os
import re
import sys
import urllib.request

# The union of the two css2 requests across the 8 pages (JetBrains Mono 700 is
# requested by the project/home pages; bio/contact omit it — the union covers all).
CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Syne:wght@500;600;700;800&"
    "family=Hanken+Grotesk:wght@400;500;600;700&"
    "family=Space+Grotesk:wght@400;500;600;700&"
    "family=Bricolage+Grotesque:opsz,wght@12..96,500;12..96,600;12..96,700&"
    "family=JetBrains+Mono:wght@400;500;600;700&"
    "family=IBM+Plex+Mono:wght@400;500;600&"
    "family=Noto+Music&display=swap"
)
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")
KEEP = {"latin", "latin-ext", "music"}
OUT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "site", "vendor", "fonts"))


def fetch(url, ua=True):
    headers = {"User-Agent": UA} if ua else {}
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=30) as r:
        return r.read()


def main():
    os.makedirs(OUT, exist_ok=True)
    css = fetch(CSS_URL).decode("utf-8")

    # Each @font-face is preceded by a /* subset */ comment.
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        print("ERROR: no @font-face blocks parsed from css2", file=sys.stderr)
        sys.exit(1)
    # Fail loudly if any @font-face was NOT paired with a recognized /* name */
    # label (e.g. Google switching to bracketed axis labels like /* [1] */),
    # so a partial, silent drop of a needed subset can never ship.
    total_faces = css.count("@font-face")
    if len(blocks) != total_faces:
        print("ERROR: paired %d of %d @font-face blocks; unrecognized subset label?"
              % (len(blocks), total_faces), file=sys.stderr)
        sys.exit(1)

    kept, downloaded = [], set()
    for subset, block in blocks:
        if subset not in KEEP:
            continue
        m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block)
        if not m:
            continue
        url = m.group(1)
        name = url.rsplit("/", 1)[-1]
        if name not in downloaded:
            data = fetch(url, ua=False)
            if data[:4] != b"wOF2":
                print("ERROR: %s did not return a woff2 (got %r)" % (url, data[:8]), file=sys.stderr)
                sys.exit(1)
            open(os.path.join(OUT, name), "wb").write(data)
            downloaded.add(name)
        kept.append("/* %s */\n%s" % (subset, block.replace(url, "/vendor/fonts/%s" % name)))

    if not kept:
        print("ERROR: kept 0 @font-face blocks (subset filter too strict?)", file=sys.stderr)
        sys.exit(1)

    # Prune woff2 no longer referenced (keeps re-runs after a font change clean).
    for stale in glob.glob(os.path.join(OUT, "*.woff2")):
        if os.path.basename(stale) not in downloaded:
            os.remove(stale)

    header = (
        "/* Self-hosted Google Fonts — latin, latin-ext, and music subsets.\n"
        "   Generated by scripts/fetch-fonts.py; do not edit by hand.\n"
        "   Families: Syne, Hanken Grotesk, Space Grotesk, Bricolage Grotesque,\n"
        "   JetBrains Mono, IBM Plex Mono, Noto Music. */\n\n"
    )
    open(os.path.join(OUT, "fonts.css"), "w").write(header + "\n".join(kept) + "\n")
    print("OK: %d @font-face blocks, %d woff2 files -> %s" % (len(kept), len(downloaded), OUT))


if __name__ == "__main__":
    main()
